// <auto-generated />
namespace MoneyTracker.DAL.PrimaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0604 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0604));
        
        string IMigrationMetadata.Id
        {
            get { return "201706042203074_0604"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
