// <auto-generated />
namespace MoneyTracker.DAL.PrimaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11102017a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11102017a));
        
        string IMigrationMetadata.Id
        {
            get { return "201711110530363_11102017a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
