// <auto-generated />
namespace MoneyTracker.DAL.PrimaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11122017b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11122017b));
        
        string IMigrationMetadata.Id
        {
            get { return "201711152126373_11122017b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
