// <auto-generated />
namespace MoneyTracker.DAL.PrimaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06025));
        
        string IMigrationMetadata.Id
        {
            get { return "201706022318058_06025"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
