// <auto-generated />
namespace MoneyTracker.DAL.PrimaryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12052018a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12052018a));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061743416_12052018a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
